name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.2
          
      - name: Check out into the root
        uses: actions/checkout@v3

      - name: Run Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.2
      
      - name: Check out into the root
        uses: actions/checkout@v3

      - name: Test
        run: go test -v ./... -coverprofile=cover.txt -covermode=atomic

      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cover.txt
